schema_version = "1.0.0"

id = "use_for_rendering_plus"
version = "1.1.0"
name = "View Layer Plus"
tagline = "Seamlessly extend View Layers management"
maintainer = "Lukas Sabaliauskas <lukas_sabaliauskas@hotmail.com>"
type = "add-on"
tags = ["Compositing", "User Interface"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "**/*.psd"
]